use_frameworks!

platform :ios, '8.0'

target 'LTSubSDKDemo_Example' do
  pod 'LTSubSDKDemo', :path => '../'

  target 'LTSubSDKDemo_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
